spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
      name: demoservice
      
server:
   port: 8080

logging:
    console:
        immediateFlush: true
    level:
       org.springframework.security: ERROR
       org.springframework.web: ERROR
       org.hibernate: ERROR
    root: Info
    file: c:/users/sathishkumar_s/Desktop/mylog.log
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger : %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger : %msg%n"
      

# create and drop tables and sequences, loads import.sql
spring.jpa:
  hibernate.ddl-auto: create-drop
  properties:
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
  show-sql: true
  database-platform: org.hibernate.dialect.Oracle10gDialect
  hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
  hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

spring.datasource:
  driverClassName: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521/xe
  username: system
  password: admin
  
  # HikariCP settings
  hikari:
    connection-timeout: 30000
    maximum-pool-size: 50
---
spring:
   profiles: dev
   application:
      name: dev_demoservice
server:
   port: 9090

---
spring: 
   profiles: prod
   application:
      name: prod_demoservice
server: 
   port: 4431  

  
  
  




  